'use client';

import React, { useState } from 'react';
import {
  FiMic,
  FiShare2,
  FiVideo,
  FiFileText,
  FiCheck,
  FiArrowRight,
} from 'react-icons/fi';
import Link from 'next/link';

interface Pillar {
  id: string;
  name: string;
  icon: React.ComponentType<{ className?: string }>;
  tagline: string;
  description: string;
  points: string[];
  ctaText: string;
  ctaHref: string;
}

const PILLARS: Pillar[] = [
  {
    id: 'voice',
    name: 'Multi-Model Voice Studio',
    icon: FiMic,
    tagline: 'Ultra-realistic neural speech synthesis powered by top-tier AI models',
    description:
      'Synthesize human-grade speech using ElevenLabs, Fish Audio, and Google Gemini with zero latency bottlenecks. Tailor voice pacing, pitch, and format for vertical Reels or long-form YouTube documentaries.',
    points: [
      '54+ natural studio voices across diverse accents and genders',
      'Dual video format presets (9:16 vertical Shorts & 16:9 widescreen)',
      'Uncompressed, crystal-clear 24kHz studio WAV audio exports',
      'Instant cloud syncing + 100% offline local workspace storage',
    ],
    ctaText: 'Open Voice Studio',
    ctaHref: '/admin',
  },
  {
    id: 'social',
    name: 'Facebook & Instagram Automation',
    icon: FiShare2,
    tagline: 'Direct 1-click social publishing and scheduling up to 75 days ahead',
    description:
      'Connect your verified Facebook Pages and linked Instagram Business accounts. Compose updates, attach synthesized video voiceovers, and schedule posts into the future.',
    points: [
      'Native Facebook Pages & Instagram Business account auto-linking',
      'Realistic desktop feed, mobile feed, and 9:16 Reel preview simulators',
      'Scheduled post manager with cancel, reschedule, and retry handlers',
      'Secure server-side token management with strict user authorization',
    ],
    ctaText: 'Explore Meta Studio',
    ctaHref: '/facebook/integration',
  },
  {
    id: 'youtube',
    name: 'YouTube Content Strategy',
    icon: FiVideo,
    tagline: 'Orchestrate long-form video scripts and viral Shorts hooks in one place',
    description:
      'Turn conceptual topics into comprehensive video strategies. Plan full chapter breakdowns, generate high-retention 3-second Shorts hooks, and transfer scripts into audio with one click.',
    points: [
      'Complete documentary and tutorial scripting framework',
      'Multi-Shorts hook extraction from long-form video concepts',
      'Direct 1-click bridge to ElevenLabs & multi-model speech synthesis',
      'Status tracking across script development and voiceover recording',
    ],
    ctaText: 'View YouTube Strategies',
    ctaHref: '/youtube/templates',
  },
  {
    id: 'json',
    name: 'JSON Campaign Engine',
    icon: FiFileText,
    tagline: 'Prompt any external LLM, paste JSON, and watch campaigns come alive',
    description:
      'Ask Claude, ChatGPT, or DeepSeek for a 30-day social calendar. Paste the raw JSON output into GenZee to instantly generate visual interactive cards with day-by-day scripts.',
    points: [
      'Compatible with JSON generated by any modern AI model',
      'Inline editable textareas and 1-click script copy buttons',
      'Direct transfer of daily scripts to Voiceover Generator',
      'Reusable templates library for 1-click campaign generation',
    ],
    ctaText: 'Launch JSON Generator',
    ctaHref: '/json-generator',
  },
];

export default function LandingFeatureShowcase() {
  const [activePillar, setActivePillar] = useState<Pillar>(PILLARS[0]);

  return (
    <section id="features" className="py-16 sm:py-20 lg:py-24">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Heading - Clean typography, zero AI chips */}
        <div className="text-center max-w-3xl mx-auto space-y-4 mb-12">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-slate-900">
            One Unified Workspace for All Creator Workflows
          </h2>
          <p className="text-base sm:text-lg text-slate-600 leading-relaxed max-w-2xl mx-auto">
            Everything you need to write, synthesize, plan, and automate your multi-channel video content.
          </p>
        </div>

        {/* Tab Switcher */}
        <div className="flex items-center justify-center gap-2 mb-10 overflow-x-auto pb-2 scrollbar-none">
          {PILLARS.map((p) => {
            const Icon = p.icon;
            const isActive = activePillar.id === p.id;
            return (
              <button
                key={p.id}
                onClick={() => setActivePillar(p)}
                className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs sm:text-sm font-semibold transition-all cursor-pointer shrink-0 ${isActive
                  ? 'bg-slate-900 text-white shadow-xs'
                  : 'bg-white text-slate-700 hover:bg-slate-100 border border-slate-200/80 shadow-2xs'
                  }`}
              >
                <Icon className={isActive ? 'text-[#ff7d6e]' : 'text-slate-400'} />
                <span>{p.name}</span>
              </button>
            );
          })}
        </div>

        {/* Pillar Showcase Card (Clean single-level container, no nested borders) */}
        <div className="bg-white border border-slate-200/80 rounded-2xl p-6 sm:p-10 shadow-xs max-w-4xl mx-auto">
          <div className="space-y-6">
            <div>
              <h3 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
                {activePillar.name}
              </h3>
              <p className="text-sm sm:text-base font-medium text-[#c83a2a] mt-1">
                {activePillar.tagline}
              </p>
            </div>

            <p className="text-sm sm:text-base text-slate-600 leading-relaxed max-w-3xl">
              {activePillar.description}
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5 pt-2">
              {activePillar.points.map((pt, idx) => (
                <div key={idx} className="flex items-start gap-3 text-xs sm:text-sm text-slate-700 bg-slate-50/70 p-3.5 rounded-xl border border-slate-100">
                  <div className="w-5 h-5 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0 mt-0.5">
                    <FiCheck className="text-xs" />
                  </div>
                  <span className="font-medium leading-snug">{pt}</span>
                </div>
              ))}
            </div>

            <div className="pt-2">
              <Link
                href={activePillar.ctaHref}
                className="inline-flex items-center gap-2 px-6 py-3 bg-[#ff7d6e] hover:bg-[#e04836] text-white rounded-xl text-xs sm:text-sm font-semibold shadow-xs hover:shadow transition-all cursor-pointer"
              >
                <span>{activePillar.ctaText}</span>
                <FiArrowRight />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
