'use client';

import React from 'react';
import Link from 'next/link';

const values = [
  {
    title: 'Creator-First',
    text: 'Every feature is designed around the daily workflow of YouTubers, Instagram creators, podcasters and social media managers, with fewer tabs, fewer exports and faster publishing.',
  },
  {
    title: 'Studio-Grade Quality',
    text: 'We focus on premium AI voice technology from ElevenLabs, Fish Audio and Google Gemini so your voiceovers sound natural, expressive and ready for monetized content.',
  },
  {
    title: 'Fair, Transparent Pricing',
    text: 'No locked subscriptions. GenZee uses a simple Pay-As-You-Go credit wallet: top up when you need to, and only pay for what you generate.',
  },
  {
    title: 'Privacy & Trust',
    text: 'Your scripts, audio and connected social accounts belong to you. We keep data handling minimal, transparent and secure.',
  },
];

const features = [
  {
    title: 'Multi-Model AI Voice Generator',
    text: 'Convert scripts into lifelike text-to-speech voiceovers in dozens of languages and styles, then download studio-grade WAV audio for Premiere Pro, CapCut, DaVinci Resolve or Final Cut Pro.',
  },
  {
    title: 'Facebook & Instagram Reels Scheduler',
    text: 'Connect your Facebook Pages and linked Instagram Business accounts, preview posts in realistic feed and Reel layouts, and publish or schedule with 1-Click Social Publishing.',
  },
  {
    title: 'AI Content Strategy Planner',
    text: 'Paste a multi-week content plan generated by any AI assistant and instantly turn it into an interactive calendar of scripts, hooks, captions and hashtags.',
  },
  {
    title: 'Campaign Automation for Agencies',
    text: 'Manage multiple channels, batch-generate voiceovers and keep every client campaign organized from one clean dashboard.',
  },
];

export default function AboutUsContent() {
  return (
    <div className="space-y-10">
      <header className="space-y-4">
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900 text-center">
          About GenZee Video: The All-in-One AI Content Studio
        </h1>
        <p className="text-base sm:text-lg text-slate-600 leading-relaxed">
          Welcome to <strong className="text-slate-900">GenZee Video</strong> (genzee.video). Our mission is to
          empower creators, agencies and modern marketers with a single studio for AI voice generation, content
          planning and social media publishing. We bridge the gap between a raw creative idea and a published
          video by combining multi-model voice synthesis with direct Facebook, Instagram and YouTube workflow
          automation.
        </p>
      </header>

      <section className="space-y-3" aria-labelledby="our-story">
        <h2 id="our-story" className="text-2xl font-bold text-slate-900">
          Our Story
        </h2>
        <p className="text-slate-600 leading-relaxed">
          GenZee started with a simple frustration: producing one short-form video meant juggling a text-to-speech
          tool, a spreadsheet for content ideas, an audio editor and a separate scheduler for each social network.
          Creators were spending more time moving files around than creating. We built GenZee to put the entire
          pipeline of script, AI voiceover, preview and publish in one place.
        </p>
        <p className="text-slate-600 leading-relaxed">
          Today, thousands of scripts, voiceovers and scheduled posts flow through the studio, helping solo
          creators publish consistently and helping agencies serve more clients without growing their team.
        </p>
      </section>

      <section className="space-y-3" aria-labelledby="mission-vision">
        <h2 id="mission-vision" className="text-2xl font-bold text-slate-900">
          Our Mission &amp; Vision
        </h2>
        <p className="text-slate-600 leading-relaxed">
          <strong className="text-slate-900">Mission:</strong> make professional-quality AI voiceovers and
          automated social publishing accessible to every creator, regardless of budget or technical skill.
        </p>
        <p className="text-slate-600 leading-relaxed">
          <strong className="text-slate-900">Vision:</strong> become the most trusted AI content studio for
          creators worldwide, where an idea becomes a polished, published video in minutes, not days.
        </p>
      </section>

      <section className="space-y-4" aria-labelledby="what-we-offer">
        <h2 id="what-we-offer" className="text-2xl font-bold text-slate-900">
          What GenZee Offers
        </h2>
        <div className="grid sm:grid-cols-2 gap-4">
          {features.map((f) => (
            <article key={f.title} className="p-5 rounded-2xl bg-slate-50/60 border border-slate-200/80 space-y-2">
              <h3 className="text-base font-bold text-slate-800">{f.title}</h3>
              <p className="text-sm text-slate-600 leading-relaxed">{f.text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="space-y-4" aria-labelledby="core-values">
        <h2 id="core-values" className="text-2xl font-bold text-slate-900">
          Our Core Values
        </h2>
        <div className="grid sm:grid-cols-2 gap-4">
          {values.map((v) => (
            <article key={v.title} className="p-5 rounded-2xl bg-slate-50/60 border border-slate-200/80 space-y-2">
              <h3 className="text-base font-bold text-slate-800">{v.title}</h3>
              <p className="text-sm text-slate-600 leading-relaxed">{v.text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="space-y-3" aria-labelledby="who-its-for">
        <h2 id="who-its-for" className="text-2xl font-bold text-slate-900">
          Who Uses GenZee?
        </h2>
        <ul className="list-disc pl-6 space-y-2 text-slate-600 leading-relaxed">
          <li>YouTubers creating faceless channels, documentaries and explainer videos.</li>
          <li>Instagram and Facebook Reels creators who need daily, consistent content.</li>
          <li>Podcasters, audiobook authors and e-learning course creators.</li>
          <li>Digital marketing agencies managing multiple brands and campaigns.</li>
          <li>Small businesses producing ads, product videos and customer announcements.</li>
        </ul>
      </section>

      <section className="space-y-3" aria-labelledby="get-in-touch">
        <h2 id="get-in-touch" className="text-2xl font-bold text-slate-900">
          Get in Touch
        </h2>
        <p className="text-slate-600 leading-relaxed">
          Have a question or an idea? Visit our{' '}
          <Link href="/faq" className="text-[#c83a2a] hover:underline font-semibold">
            FAQ
          </Link>{' '}
          or{' '}
          <Link href="/contact-us" className="text-[#c83a2a] hover:underline font-semibold">
            contact our team
          </Link>
          . We read every message.
        </p>
      </section>
    </div>
  );
}
